
default-target = "wasm32-unknown-emscripten"
prepend-js = "src/setup.js"

[target.emscripten]

link-args = [
"-s","USE_WEBGL2=1",
"-s","FULL_ES3=1",
"-s","ALLOW_MEMORY_GROWTH=1",

"-s","ASSERTIONS=2",

"-s","SAFE_HEAP=1",
#"-s","DETERMINISTIC=1",
#"-s","EMULATE_FUNCTION_POINTER_CASTS=1",
#"-s","BINARYEN_METHOD=\"native-wasm\"",

#"-s","USE_PTHREADS=1",
#"-s", "WASM_MEM_MAX=1536MB",


]