[package]
name = "mapbox-tiles"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]

[dependencies]
common={path= "../common"}
prost="*"

prost-derive = "*"

prost-types = "*"
bytes = "*"

[build-dependencies]
prost-build="*"